version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # see if the es cluster is available
      - run: .circleci/wait_es_up.sh

      # enable xdebug
      - run: sudo ln -s /etc/php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
      - run: php --ini

      # run tests!
      - run: vendor/bin/phpunit

      # run coverage
      - run: bash <(curl -s https://codecov.io/bash)

  analyze_phpcs:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run code analyzer
      - run: vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 src
      - run: vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 tests

  analyze_phpstan:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run code analyzer
      - run: vendor/bin/phpstan analyse --level 7 -c phpstan.neon src tests
  analyze_eol:
    docker:
      - image: nexucis/ci-checkfiles
    working_directory: ~/repo
    steps:
      - checkout
      - run: checkEOL *.php *.md *.xml *.sh composer.json phpstan.neon

  analyze_encoding_utf8:
    docker:
      - image: nexucis/ci-checkfiles
    working_directory: ~/repo
    steps:
      - checkout
      - run: checkEncoding utf-8 *.php *.md *.xml *.sh composer.json phpstan.neon

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - analyze_phpcs:
          requires:
            - build
      - analyze_phpstan:
          requires:
            - build
      - analyze_eol:
          requires:
            - build
      - analyze_encoding_utf8:
          requires:
            - build