# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.8-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
      - image: elasticsearch:2.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # see if the es cluster is available
      - run: .circleci/wait_es_up.sh

      # enable xdebug
      - run: sudo ln -s /etc/php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
      - run: php --ini

      # run tests!
      - run: vendor/bin/phpunit

      # run coverage
      - run: bash <(curl -s https://codecov.io/bash)

  analyze:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run code analyzer
      - run: vendor/bin/phpcs --standard=PSR2 --extensions=php --encoding=utf-8 --tab-width=4 src
      - run: vendor/bin/phpcs --standard=PSR2 --extensions=php --encoding=utf-8 --tab-width=4 tests

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - analyze